### ISSUE TITLE
New API Key Support

### ISSUE THREAD

**Issue by mackenly** [shauntarves/wyze-sdk#135]
Wyze has announced official support for creating API keys in this announcement:

https://support.wyze.com/hc/en-us/articles/16129834216731?lid=87ac6t8mqos0

**Comment by holocronology** [comment]
It is interesting that they have removed the references to Home Assistant which were originally on that page on in the email that was sent.

**Comment by romedtino** [comment]
> It is interesting that they have removed the references to Home Assistant which were originally on that page on in the email that was sent.

I noticed that too... Maybe they're working with HA directly to add their own integration? Lol wishful thinking. The thing with this API, it's nice to have an access token and refresh token which probably helps relieve load to their login servers but are they planning to offer actual endpoints and documentions to actually access devices? Making any integration less hacked/guessed? 🤞 Here's to hoping something good upcoming

**Comment by shauntarves** [comment]
Hey folks...just published v2.0.0 thanks to @mrlt8's contribution. You will need to generate the API key on Wyze's site and feed it into the client constructor in order to login and create the new access token.

I'm honored that so many folks rely on this to control their homes - that's a lot of pressure 🤣
