### ISSUE TITLE
copy files from the Wyze V3 cam onto my laptop

### ISSUE THREAD

**Issue by david-olshefski** [shauntarves/wyze-sdk#136]
I'd like to copy over the files, directly from the Wyze v3 camera SDCARD to my laptop.  I don't want to view the live stream, I just
would like to FTP all the files.  Right now, I have to manually remove the SDCARD form the camera, put it into my laptop, copy the files over, then put the SDCARD back into the camera.  Does anyone know of a way to obtain the files, similar to FTP?

**Comment by shauntarves** [comment]
I doubt that is possible. The support/access for the cameras is already VERY limited because the cameras use a proprietary, java-based protocol for communication. I doubt the cameras themselves allow for any kind of telnet, ftp, or ssh access.

**Comment by robughblah** [comment]
wyze mini hacks can enable ssh to the wyze cameras, and file transfer and much more. gtxaspec/wz_mini_hacks: wz camera mods... make your camera better.github.comRobOn Jan 13, 2024, at 2:30 PM, Shaun Tarves ***@***.***> wrote:﻿
I doubt that is possible. The support/access for the cameras is already VERY limited because the cameras use a proprietary, java-based protocol for communication. I doubt the cameras themselves allow for any kind of telnet, ftp, or ssh access.
