### ISSUE TITLE
Vacuum voltage/Battery not showing again.  

### ISSUE THREAD

**Issue by bdwilson** [shauntarves/wyze-sdk#34]
vacuum.voltage = 100 on 1.0.1
vacuum.voltage = None on 1.2.1
 
This has been an issue before: https://github.com/shauntarves/wyze-sdk/issues/9

**Comment by romedtino** [comment]
If you want to temporarily work around this and modify your site-packages/wyze_sdk copy, you can change 

https://github.com/shauntarves/wyze-sdk/blob/master/wyze_sdk/models/devices/vacuums.py#L542 from:

```python
        self.voltage = super()._extract_property(VacuumProps.battery(), others)      
```

to

```python
        self.voltage = DeviceProp(definition=VacuumProps.battery(), value=super()._extract_attribute("battary" if "battary" in others else VacuumProps.battery().pid, others))
```

Not too great with my python and the code shaun has is a bit complicated for me but I think the issue is `device_params` exists in `others` when calling `_extract_property` which ends up returning `device_params` contents instead of `battary`'s which would have happened in line 349 of base.py

I think shauntarves said he's working on fixes for a bunch of these things and he just needs some time. so I'm not sure if he's willing to take some PRs with these tweaks to fix some things but I think pypi would still need to be updated by him after the fact. 

Good luck!
