### ISSUE TITLE
Wrong package for PyPi

### ISSUE THREAD

**Issue by boilerbots** [shauntarves/wyze-sdk#62]
Your PyPi package command should be `pip install wyze-sdk`  you might want to fix that in case someone hijacks that other.

**Comment by shauntarves** [comment]
Hi @boilerbots ,

I appreciate the concern! Best I can tell, pypi actually has associated my project with the `_` version as well. Notice that https://pypi.org/project/wyze_sdk/ redirects to https://pypi.org/project/wyze-sdk/ and either version in the command `pip install wyze_sdk` or `pip install wyze-sdk` install my project correctly.

I'm not entirely sure why this is or if I happened into it because the actual module in my wheel is `wyze_sdk` even though I opted for the package name `wyze-sdk`, but I'll take it!
