### ISSUE TITLE
Wyze Vacuum Beta Firmware Bug - Multi Level Floors

### ISSUE THREAD

**Issue by romedtino** [shauntarves/wyze-sdk#63]
I think with the newer/beta version of the Wyze Vacuum, the protobuf map definition [_robot_map_proto](https://github.com/shauntarves/wyze-sdk/blob/a8933f714618894a13a4d272bc2cb3c0475edd0a/wyze_sdk/models/devices/vacuums.py#L218) has changed so some users are experiencing crashing when asking for `sweep_rooms`

See here for examples of crashing - https://github.com/romedtino/simple-wyze-vac/issues/9

I'm not too familiar with how it all ties together but I know in the beta firmware they are testing multi-level maps so I'm thinking it's most likely because of this.

**Comment by shauntarves** [comment]
Hi @romedtino,

Thanks for reporting this. I haven't tried the new firmware on my own vacuum, but someone else reported this same issue so I don't mind give it a look.

Bear with me while I find a little bit of time to work on it.

**Comment by romedtino** [comment]
Awesome to hear you're still around! Really love your work here. Makes owning Wyze products more interesting to use 🥳

**Comment by romedtino** [comment]
I have been avoiding that firmware since it's been in beta for so long now and it feels like Wyze is having issues with it x_X... as far as I know there isn't an easy way to rollback either so I don't think I can test this out for you. Sorry!

**Comment by shauntarves** [comment]
Oh this is super helpful. No one else has chimed in that actually is
running that firmware.

The original issue(s) were around the map being improperly parsed in
certain conditions. I don't think this was directly related to multi-floor
mappings, but rather to changes in the protobuf structure over time.

I actually have not ever understood *what* was needed to "support"
multi-floor. But, from what you are saying, you simply need to be able to
set which map the vacuum thinks is current? Without the multi-floor map
firmware, I've not ever seen what that looks like from the app.

If there's anything I'm missing, please let me know. However, in order to
resolve this, I'll need you to share the vacuum with my wyze account
temporarily so I can see what the map options are. My account is shaun <at>
tarves <dot> net
