### ISSUE TITLE
Off after time stopped working

### ISSUE THREAD

**Issue by Sfrjoshpro** [shauntarves/wyze-sdk#86]
Was using the plug off function with time delay just fine.  One day it stopped working and I had to set rule in Wyze app to turn off now

Still can turn on and off with api just no delays

**Comment by Sfrjoshpro** [comment]
Not sure what information you all would like to see

**Comment by shauntarves** [comment]
Hey there...if you'd be able to share a plug with me, I can look into this. It's possible that my upcoming fixes for the bulb will fix this because they seem to have shifted the old devices over to a new API.

Let me know if you can do this. Otherwise, it might be some time. I don't have a plug that works right now.

**Comment by Sfrjoshpro** [comment]
Id love to work with you.   Share
The plug as in remote?

**Comment by shauntarves** [comment]
You can share it right from the app. That will give me read limited access
to some functions of the device.

If you go into the settings of the specific device, you can find the share
function.

My email is shaun <at> tarves <dot> net

**Comment by Sfrjoshpro** [comment]
Ok I’ll run out and buy one more today. I’m currently using both with their
app.
 But definitely need your api for my custom software

I’ll reach back out later today

**Comment by Sfrjoshpro** [comment]
I’ll be home in 30-40mins
