### ISSUE TITLE
Outdoor plug

### ISSUE THREAD

**Issue by Sfrjoshpro** [shauntarves/wyze-sdk#99]
It was running for maybe hour or so
Then got this issue
(
![image](https://user-images.githubusercontent.com/14016441/199104176-62505ecb-d824-4ec7-94d6-a424ce639d23.jpeg)
)

**Comment by Sfrjoshpro** [comment]
Changed from every 30s to 1min and haven't had a issue   Just 30s make it lock up

**Comment by Sfrjoshpro** [comment]
After letting it run for almost a day half at 60 sec. It got the same error

Maybe it's limit with Wyze servers

**Comment by shauntarves** [comment]
Yeah, that's what it feels like. It almost seems as if the creation of the
client is failing (probably due to excessive logins). My recommendation
would be to not create a new client continuously. The client is meant to be
long-lived, which is why there's a refresh capability to refresh the access
token.

Think of it this way: Creating a client (without passing an existing access
token) creates a new login/session on the wyze servers. That process
returns an access token and a refresh token, both of which get stored in
the client object.

Continually creating a new client would be like logging in to the wyze app
over and over again. There may be some implicit limit in their servers OR
the process is just encountering a hiccup. Either way, it's probably best
to re-architect your scripts to re-use the client and maybe refresh it once
per hour.
